version: "3.8"
services:
  back:
    depends_on:
      - db
    env_file:
      - .env
    container_name: back
    build:
      context: ./
      dockerfile: back.Dockerfile
    ports:
      - 8000:8000
    networks:
      - service

  db:
    image: mysql
    env_file:
      - .env
    restart: always
    container_name: db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - service

networks:
  service:
    driver: bridge
    external: true
    internal: true
