version: "3.8"
services:
  front:
    container_name: front
    command: npm run dev
    build:
      context: ./
      dockerfile: front.Dockerfile
    ports:
      - 3000:3000
    entrypoint: ./wait-for-it.sh back:8000
    
